# lefthook configuration
# https://github.com/evilmartians/lefthook

pre-commit:
  parallel: true
  commands:
    prettier:
      glob: '*.{js,jsx,ts,tsx,json,md,css,scss,html,yml,yaml}'
      run: npx prettier --write {staged_files}
      stage_fixed: true
    eslint:
      glob: '*.{js,jsx,ts,tsx}'
      run: npx eslint --fix {staged_files}
      stage_fixed: true
